Timely/Timely/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('_', include('django.contrib.auth.urls')),

]

Timely/main_app/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signup, name='signup'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('timezones/', views.timezones, name='timezones'),
    path('timezones/<int:timezone_id>/', views.timezones_detail, name='detail'),
    path('timezones/create/', views.TimezonesCreate.as_view(), name='timezones_create'),
    # path('timezones/<int:pk>/update/', views.TimezonesUpdate.as_view(), name='timezones_update'),
    path('timezones/<int:pk>/delete/', views.TimezonesDelete.as_view(), name='timezones_delete'),
]

Timely/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
# super user is: han, han@han.com, han123HAN


class Timezones(models.Model):
    timezone = models.ForeignKey(
        'iana_timezones', on_delete=models.CASCADE, null=True)
    hour_toggle = models.BooleanField(default=False)
    availability_start_time = models.CharField(max_length=100, default='00:00')
    availability_end_time = models.CharField(max_length=100, default='23:59')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100, default='Toronto')
    country = models.ForeignKey(
        'Country', on_delete=models.CASCADE, null=True, default='Canada')
    name = models.CharField(max_length=100, default='Princeton')

    def __str__(self):
        return self.name + ' - ' + str(self.timezone) + ' - ' + str(self.city) + ' - ' + self.availability_start_time + ' - ' + self.availability_end_time + ' - ' + str(self.hour_toggle)


class iana_timezones(models.Model):
    iana_timezone = models.CharField(max_length=100)

    def __str__(self):
        return self.iana_timezone


class City(models.Model):

    city_name = models.CharField(max_length=100)

    def __str__(self):  # show the actual city name on the dashboard
        return self.city_name

    class Meta:  # show the plural of city as cities instead of citys
        verbose_name_plural = 'cities'


class Country(models.Model):
    country_name = models.CharField(max_length=100)
    country_short_name = models.CharField(max_length=100)
    country_phone_code = models.CharField(max_length=100)

    def __str__(self):
        return self.country_name

Timely/main_app/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import requests
from .models import *
from .forms import CityForm
import pendulum


from django.contrib.auth.forms import UserCreationForm
# Add the following import


# Define the home view


def home(request):
    return render(request, 'home.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()

            return redirect('/login')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def login(request):
    return render(request, 'registration/login.html')


@login_required
def timezones(request):
    timezones = Timezones.objects.filter(
        user=request.user)  # returns all timezones

    # Enter your API key here
    api_key = "ea43d349fe09f49a0d21b5607b77208c"

    url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=" + api_key

    if request.method == 'POST':  # only true if form is submitted
        # add actual request data to form for processing
        form = CityForm(request.POST)
        form.save()  # will validate and save if validate

    form = CityForm()

    timezones_dto_data = []

    timezones_data = []
    name_data = []
    city_data = []
    country_code = []
    start_data = []
    end_data = []
    sunrise_sundown_data = [100, 50]
    timezones_id = []

    for timezone in timezones:
        timezones_arr = str(timezone).split('-')
        name_data.append("".join(timezones_arr[0].split()))
        timezones_data.append("".join(timezones_arr[1].split()))
        city_data.append(timezones_arr[2])
        start_data.append("".join(timezones_arr[3].split()))
        end_data.append("".join(timezones_arr[4].split()))
        timezones_id.append(timezone.id)
        country_code.append(timezone.country.country_short_name)

    for i, city in enumerate(city_data):

        # request the API data and convert the JSON to Python data types
        city_weather = requests.get(url.format(city, country_code[i])).json()
        # print(city_weather)

        data_object = {
            'city': city,
            'country': city_weather['sys']['country'],
            'temperature': city_weather['main']['temp'],
            'feels_like': '',
            'temperature_rounded': round(city_weather['main']['temp']),
            'description': city_weather['weather'][0]['main'],
            'time': (pendulum.now(timezones_data[i])).strftime("%H:%M"),
            'icon': city_weather['weather'][0]['icon'],
            'name': name_data[i],
            'start_time': start_data[i],
            'end_time': end_data[i],
            'id': timezones_id[i],
        }

        temperature_comparison = round(city_weather['main']['temp'])
        feels_like_comparison = round(city_weather['main']['feels_like'])

        if temperature_comparison == feels_like_comparison:
            data_object['feels_like'] = 'Feels similar'
        elif temperature_comparison > feels_like_comparison:
            data_object['feels_like'] = 'Feels cooler'
        elif temperature_comparison < feels_like_comparison:
            data_object['feels_like'] = 'Feels warmer'

        timezones_dto_data.append(data_object),

    # for sunrise and sundown progressbar
    # if timezones_data is not empty

    if timezones_data:
        city_weather = requests.get(url.format(city_data[0])).json()
        sr = pendulum.from_timestamp(
            city_weather['sys']['sunrise'], tz=timezones_data[0])

        sd = pendulum.from_timestamp(
            city_weather['sys']['sunset'], tz=timezones_data[0])

        curr = pendulum.now(timezones_data[0])
        total_diff = sd.diff(sr).in_hours()
        current_diff = sr.diff(curr).in_hours()
        sunrise_sundown_data[0] = total_diff
        sunrise_sundown_data[1] = current_diff

    # creating timezoneDTO

    timezoneDTO = {
        'timezones': timezones_dto_data,
        'sunrise_sundown': sunrise_sundown_data,

    }

    return render(request, 'timezones.html', timezoneDTO)


class TimezonesCreate(CreateView):
    model = Timezones
    fields = ['country', 'city', 'timezone',
              'availability_start_time', 'availability_end_time', 'name']
    success_url = '/timezones/'

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the timezone
        # Let the CreateView do its job as usual
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context["country_list"] = Country.objects.all()
        context["timezone_list"] = iana_timezones.objects.all()
        return context


class TimezonesDelete(DeleteView):
    model = Timezones
    success_url = '/timezones/'


def timezones_detail(request, timezone_id):
    timezone = Timezones.objects.get(id=timezone_id)
    timezone_data = {
        'timezone': timezone,
    }
    return render(request, 'timezones_detail.html', timezone_data)

Timely/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Timely</title>
  <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul class="right">

        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Timely &nbsp;</div>
  </footer>
</body>

</html>

Timely/main_app/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Timely</title>
  <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
</head>

<body>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <h3 class="right">All Rights Reserved. &copy; 2022 Timely &nbsp;</h3>
  </footer>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="{% static '/main.js' %}" type="text/javascript" charset="utf-8"></script>
</body>

</html>

Timely/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Login</h1>

{% endblock %}

Timely/main_app/templates/main_app/city.html
<div class="column is-offset-4 is-4">
    <form method="POST">
        {% csrf_token %}
        <div class="field has-addons">
            <div class="control is-expanded">
                <input class="input" type="text" placeholder="City Name">
            </div>
            <div class="control">
                <button class="button is-info">
                    Add City
                </button>
            </div>
        </div>
    </form>
</div>

Timely/main_app/templates/main_app/timezones_confirm_delete.html
{% extends 'header.html' %}
{% block content %}
{% load static %}
<div class="login-wrapper">

    <div class="gradient-container-delete fade-in">
        <h1>Delete Timezone</h1>
        <h3 class="subheading-white">Are you sure you want to delete<br>
            <span class="teal-text">{{ object.name }}</span>'s
            Timezone?
        </h3>
        <div class="delete-window">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" value="Yes, delete" class="btn-delete ">
                <input type="hidden" name="next" value="{{ next }}">

            </form>
            <a href="{% url 'timezones' %}">
                <h3 class="subheading-white">No, cancel</h3>
            </a>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

Timely/main_app/templates/main_app/timezones_form.html
{% extends 'header.html' %}
{% block content %}
{% load static %}
<div class="login-wrapper">

    <div class="gradient-container-add fade-in">
        <h1>Add a Timezone</h1>
        <div class="delete-window">
            <div class="signup-form">
                <form action="" method="post">
                    <!-- Django requires the following for security purposes -->
                    {% csrf_token %}
                    <label class="subheading-white">Name</label>
                    <input type="text" name="name" value="Princeton" maxlength="100" required="" id="id_name">
                    <!-- Render the inputs inside of <tr>s & <td>s -->
                    <label class="subheading-white">Country & City</label>
                    <select name="country" id="id_country">
                        {% for country in country_list %}
                        <option value="{{ country.id }}">{{ country.country_name }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" name="city" value="Toronto" maxlength="100" required="" id="id_city">
                    <label class="subheading-white">Timezone</label>
                    <select name="timezone" required="" id="id_timezone">
                        {% for timezone in timezone_list %}
                        <option value="{{ timezone.id }}">{{ timezone.iana_timezone }}</option>
                        {% endfor %}

                    </select>
                    <label class="subheading-white">Availability in Local Time</label>
                    <input type="text" name="availability_start_time" value="00:00" maxlength="100" required=""
                        id="id_availability_start_time">
                    <input type="text" name="availability_end_time" value="23:59" maxlength="100" required=""
                        id="id_availability_end_time">

                    <input type="submit" value="Submit" class="btn">
                </form>
            </div>
        </div>
    </div>
</div>

</main>
<footer class="page-footer">
    <h3 class="right">All Rights Reserved. &copy; 2022 Timely &nbsp;</h3>
</footer>
</body>
{% endblock %}
<script defer>

    async function getToken(url = 'https://www.universal-tutorial.com/api/getaccesstoken') {
        // Default options are marked with *
        const response = await fetch(url, {
            method: 'GET', // *GET, POST, PUT, DELETE, etc.
            headers: {
                "Accept": "application/json",
                "api-token": "QZX-86Feq0Pkxbk0VRntPOaq7uS58qkEq1Iym7aMAAINRrDi1i8k6P6SMDAebSw3cbs",
                "user-email": "hanming497@gmail.com"
                // 'Content-Type': 'application/x-www-form-urlencoded',
            }

        });
        return response.json();
    }

    async function getStates(country) {
        const auth = await getToken();
        url = 'https://www.universal-tutorial.com/api/states/' + country;
        const response = await fetch(url, {
            method: 'GET', // *GET, POST, PUT, DELETE, etc.
            headers: {
                "Authorization": "Bearer " + auth['auth_token'],
                "Accept": "application/json"
            }

        });

        const data = await response.json();


        var test = document.getElementById("states_select")

        //remove options if necessary
        for (var i = test.options.length - 1; i >= 0; i--) { test.remove(i); }
        //add new options
        for (i in data) { test.add(new Option(data[i].state_name, data[i].state_name)); }

    }

    async function getCities(state) {


        stateStripped = encodeURI(state);
        console.log(stateStripped);
        const auth = await getToken();
        url = 'https://www.universal-tutorial.com/api/cities/' + stateStripped;
        const response = await fetch(url, {
            method: 'GET', // *GET, POST, PUT, DELETE, etc.
            headers: {
                "Authorization": "Bearer " + auth['auth_token'],
                "Accept": "application/json"
            }

        });
        console.log(response)
        const data = await response.json();

        console.log(data)
        var test = document.getElementById("id_city")

        //remove options if necessary
        for (var i = test.options.length - 1; i >= 0; i--) { test.remove(i); }
        //add new options
        for (i in data) { test.add(new Option(data[i].city_name, data[i].city_name)); }

    }


</script>

</html>

Timely/main_app/templates/timezones.html
{% extends 'header.html' %}
{% block content %}
{% load static %}
{% if user.is_authenticated %}
<div class="timezone-wrapper">
    <div class="nav-container">
        <img src="{% static 'img/timelylogo-sideways.svg' %}" alt="Timely logo">
        <div class="slidecontainer">
            <img src="{% static 'img/sun.svg' %}" alt="Timely logo">
            <input type="range" min="0" max={{sunrise_sundown.0}} value={{sunrise_sundown.1}} class="slider"
                id="myRange">
            <img src="{% static 'img/crescent-moon.svg' %}" alt="Crescent Moon">
            <h3>NOW</h3>
        </div>


        <div class="settings">
            <h3>EDIT</h3>
            <hr class="rotated">
            <a href="settings">
                <img src="{% static 'img/cog.svg' %}" alt="Settings Cog">
            </a>
            <hr class="rotated">
            <a href="{% url 'logout' %}">
                <img class="logout" src="{% static 'img/logout.svg' %}" alt="Logout">
            </a>
        </div>
    </div>

    <div class="timezone-tile-container">
        {% for timezone in timezones %}
        {% if forloop.counter == 4 %}
        <div class="tile tile-weather">
            <a href="{% url 'timezones_delete' timezone.id %}">
                <input type="button" name="closeMessage" value="×" id="closeMessage">
            </a>
            <div class="timezone-content">
                <div id="location">{{ timezone.city }}, {{ timezone.country }}

                </div>
                <div id="user-time">
                    <h1 class="localtime">{{timezone.time}}</h1>
                    <h1>{{timezone.name}}</h1>
                </div>
                <div class="weather-content">


                    <div id="weathercondition">
                        <div id="temperature">{{ timezone.temperature_rounded }}°C</div>
                        <div id="tempFahrenheit"></div>
                        <hr>
                        <div id="temperaturecondition">{{ timezone.description }}</div>
                    </div>
                    <div id="feelslike">{{timezone.feels_like}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if forloop.counter <= 3 %} <div class="tile tile-weather">
            <a href="{% url 'timezones_delete' timezone.id %}">
                <input type="button" name="closeMessage" value="×" id="closeMessage">
            </a>
            <div class="timezone-content">
                <div id="location">{{ timezone.city }}, {{ timezone.country }}</div>
                <div id="user-time">
                    <h1 class="localtime">{{timezone.time}}</h1>
                    <h1>{{timezone.name}}</h1>
                </div>
                <div class="weather-content">


                    <div id="weathercondition">
                        <div id="temperature">{{ timezone.temperature_rounded }}°C</div>
                        <div id="tempFahrenheit"></div>
                        <hr>
                        <div id="temperaturecondition">{{ timezone.description }}</div>
                    </div>
                    <div id="feelslike">{{timezone.feels_like}}</div>
                </div>
            </div>
            {% if forloop.last %}
    </div>
    <a href="{% url 'timezones_create' %}">
        <div class="tile tile-add-timezone">
            <div class="timezone-content">
                <div id="empty_timezone">

                    <h3 class="subheading">ADD A PERSON’S <br>TIMEZONE <br>AND
                        AVAILABILITY</h3>
                    <img style="padding: 30px" src="{% static 'img/plus.svg' %}" alt="Plus sign">
                </div>
            </div>
        </div>
    </a>
    {%endif%}
</div>
{% endif %}
{% empty %}
<a href="{% url 'timezones_create' %}">
    <div class="tile tile-add-timezone">
        <div class="timezone-content">
            <div id="empty_timezone">

                <h3 class="subheading">ADD A PERSON’S <br>TIMEZONE <br>AND
                    AVAILABILITY</h3>
                <img style="padding: 30px" src="{% static 'img/plus.svg' %}" alt="Plus sign">

            </div>
        </div>
    </div>
</a>
{% endfor %}
</div>
</div>

{% else %}
<li><a href="{% url 'login' %}">Log In</a></li>
{% endif %}
</div>
</div>
{% endblock %}

Timely/main_app/templates/timezones_detail.html
{% extends 'header.html' %}
{% block content %}


<div class="card">
    <div class="card-content">
        <span class="card-title">Details for {{ timezone.name }}'s Timezone</span>
        <p>
            <strong>City:</strong> {{ timezone.city }}<br>
            <strong>Timezone:</strong> {{ timezone.timezone }}<br>
            <strong>Hour Toggle:</strong> {{ timezone.hour_toggle }}<br>

            <strong>Start Time:</strong> {{ timezone.availability_start_time }}<br>
            <strong>End Time:</strong> {{ timezone.availability_end_time }}<br>
        </p>

    </div>
</div>

{% endblock %}